Ncov counts
nextstrain/counts pull request #2
Opened 2022-04-19 16:00 UTC by joverlee521

First pass of the automated pipeline for ncov counts that has scripts run directly via GitHub Action workflows. 
The current pipeline does not seem complicated enough to warrant porting to Snakemake, but it would be helpful when we want to expand counts to other pathogens and/or other clade definitions.

2022-04-27 16:24 UTC, trvrb requested changes
Great work here. Please see attached issues.

2022-04-29 01:30 UTC, joverlee521 commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f location -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
I completely missed the NYC and NY separation, this has been fixed in [19998be](https://github.com/nextstrain/counts/pull/2/commits/19998be4360ad60e4e98a8ae3ced36a92c652f48).

2022-04-29 01:32 UTC, joverlee521 commented on bin/fetch-ncov-us-case-counts
> +curl 'https://data.cdc.gov/resource/9mfq-cb36.csv?$select=submission_date,state,new_case&$where=new_case>0' \
I missed there was a default limit of 1000 records for the API, this has been fixed in [6c861ba](https://github.com/nextstrain/counts/pull/2/commits/6c861bae7eea30bd3a93171b193e90ad4ebdb74c).

2022-04-29 01:32 UTC, joverlee521 commented on bin/fetch-ncov-global-case-counts
> +    # Rename new_cases to cases
Done in [e468ddb](https://github.com/nextstrain/counts/pull/2/commits/e468ddb28edbcaa6bff94221ea1f87816679b9f6).

2022-04-29 01:33 UTC, joverlee521 commented on source-data/us-states.tsv
> +abbreviation	name
Done in [9029884](https://github.com/nextstrain/counts/pull/2/commits/9029884d64b7f256941a2fd6b66acc1be8529cec)

2022-04-29 01:40 UTC, joverlee521 commented on .github/workflows/update-ncov-gisaid-clade-counts.yaml
> +    - name: summarize global clade counts
Added the tsv-select in [a9b16e9](https://github.com/nextstrain/counts/pull/2/commits/a9b16e90ae8395307eecf71c7978d5f89afc416c).

2022-04-29 01:48 UTC, trvrb commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f location -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
Great! I didn't catch this myself until @huddlej pointed it out to me previously.

2022-04-29 01:51 UTC, trvrb commented on bin/fetch-ncov-global-case-counts
> +    # Rename new_cases to cases
Great! Thank you.

2022-04-29 01:52 UTC, trvrb commented on .github/workflows/update-ncov-gisaid-clade-counts.yaml
> +    - name: summarize global clade counts
Thank you!

2022-04-29 01:53 UTC, trvrb commented on source-data/us-states.tsv
> +abbreviation	name
Thank you!

2022-04-30 19:48 UTC, trvrb commented on bin/fetch-ncov-us-case-counts
> +curl 'https://data.cdc.gov/resource/9mfq-cb36.csv?$select=submission_date,state,new_case&$where=new_case>0' \
Great! This strategy makes sense to me.

2022-04-30 20:04 UTC, trvrb commented
Currently, sort order makes intuitive sense to me with:
```
date	location	clade	sequences
2020-05-30	Afghanistan	20A	2
2020-06-02	Afghanistan	20A	1
2020-06-06	Afghanistan	20A	2
2020-06-07	Afghanistan	20A	1
2020-06-13	Afghanistan	20A	2
2020-06-15	Afghanistan	20A	1
2021-01-21	Afghanistan	20A	16
2021-04-12	Afghanistan	20G	1
2021-04-15	Afghanistan	20G	1
2021-04-19	Afghanistan	20G	1
2021-04-20	Afghanistan	20G	1
2021-04-21	Afghanistan	20G	1
2021-03-21	Afghanistan	20I (Alpha, V1)	1
2021-03-26	Afghanistan	20I (Alpha, V1)	1
2021-04-10	Afghanistan	20I (Alpha, V1)	4
2021-04-20	Afghanistan	20I (Alpha, V1)	1
2021-04-22	Afghanistan	20I (Alpha, V1)	1
2021-04-25	Afghanistan	20I (Alpha, V1)	1
```
where we first sort by `location`, then by `clade` and last by `date`.  When I read this TSV by eye I want to look at how a particular clade behaves in a particular location through time and this sorting enables this nicely.

That said, I wonder if we should reorder columns to further emphases this sort order. This would give:
```
location	clade	date	sequences
Afghanistan	20A	2020-05-30	2
Afghanistan	20A	2020-06-02	1
Afghanistan	20A	2020-06-06	2
Afghanistan	20A	2020-06-07	1
Afghanistan	20A	2020-06-13	2
Afghanistan	20A	2020-06-15	1
Afghanistan	20A	2021-01-21	16
Afghanistan	20G	2021-04-12	1
Afghanistan	20G	2021-04-15	1
Afghanistan	20G	2021-04-19	1
Afghanistan	20G	2021-04-20	1
Afghanistan	20G	2021-04-21	1
Afghanistan	20I (Alpha, V1)	2021-03-21	1
Afghanistan	20I (Alpha, V1)	2021-03-26	1
Afghanistan	20I (Alpha, V1)	2021-04-10	4
Afghanistan	20I (Alpha, V1)	2021-04-20	1
Afghanistan	20I (Alpha, V1)	2021-04-22	1
Afghanistan	20I (Alpha, V1)	2021-04-25	1
```

What do you think @joverlee521 and @marlinfiggins?

2022-04-30 20:29 UTC, trvrb requested changes
This is looking really good. I just had the one requested change to provision cases in `nextstrain-ncov-private` and the PR comment about reordering fields.

2022-05-02 17:22 UTC, huddlej reviewed
This is really cool, @joverlee521! I used the GISAID clades as inputs for one of Marlin's modeling notebooks and everything worked as expected. I haven't had a chance to use the case counts yet, but I left some minor comments below.

2022-05-02 17:22 UTC, huddlej commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f state -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
I wish there was an option in `csvtk replace` to error on a missing key. When using `--keep-key`, it's possible a new abbreviation could appear in the data produced by the API, this script would silently work, but we'd be missing data for whatever region matches that abbreviation (e.g., if we didn't have an entry for `NYC` that maps to `New York`).

The closest I can get to an error on missing key would be to use `--key-miss-repl` instead with a placeholder like `Missing` or `NA`, etc. and then a subsequent command that asserts there are no records with that missing value. This would at least loudly break the script (and the workflow running it), so we could troubleshoot.

2022-05-02 17:22 UTC, huddlej commented on README.md
> +## Data Sources
In addition to this information about where we get the data, I would love a directory of the paths produced by this workflow. For example, I refer to [the ncov workflow's "remote inputs" page](https://docs.nextstrain.org/projects/ncov/en/latest/reference/remote_inputs.html) regularly to find the URL to a dataset I want to use. This repo could use a similar minimal reference to the available paths one could download from.

2022-05-02 17:22 UTC, huddlej commented on .github/workflows/update-ncov-case-counts.yaml
> +    - name: upload to S3
I had the same experience where I was reaching for an adjacent counts file for the clades, couldn't find it, and then realized it made sense not to duplicate it. But, duplicating it would make life easier for the user. Another option would be to include the explicit list of output paths from this workflow mentioned in the comment below for the `README.md`.

2022-05-02 17:22 UTC, huddlej commented on .github/workflows/update-ncov-open-clade-counts.yaml
> +      run: mamba install "pandas>=1.0.0" "tsv-utils"
I've loved using `tsv-utils` for this kind of work, too, but `csvtk` seems to offer all of the same functionality. Would you consider using `csvtk` throughout this repo/workflow just to simplify dependencies and make all of the scripts consistent with each other in their tooling?

2022-05-02 17:57 UTC, joverlee521 commented on .github/workflows/update-ncov-case-counts.yaml
> +    - name: upload to S3
Ah, I wish AWS S3 supported some sort of symlink for this...
If it makes sense from a user's prospective to have all the necessary data in one bucket, then I can upload the case counts to both the public and private buckets.

2022-05-02 17:57 UTC, joverlee521 commented on .github/workflows/update-ncov-case-counts.yaml
> +        requird: false
Thanks for noticing this!

2022-05-02 18:05 UTC, joverlee521 commented on .github/workflows/update-ncov-open-clade-counts.yaml
> +      run: mamba install "pandas>=1.0.0" "tsv-utils"
`tsv-utils` is [faster](https://github.com/eBay/tsv-utils/blob/master/docs/Performance.md) than `csvtk` so I opted to use it here for purely speeding up the workflow. (The workflow can technically be run without `tsv-utils`, just slower).

2022-05-02 20:43 UTC, joverlee521 commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f state -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
Yeah, I agree we don't want to be silently missing new abbreviations. Replacing new values with a placeholder seems like it would make it harder to troubleshoot. I can add in an extra step to check for new locations and notify via Slack (follows the pattern we've set up for ncov-ingest).

2022-05-02 23:40 UTC, joverlee521 commented on .github/workflows/update-ncov-case-counts.yaml
> +        requird: false
Fixed in [0c9d736](https://github.com/nextstrain/counts/pull/2/commits/0c9d736e7c0eaec79398019afed7ce1d1fa5d27b).

2022-05-02 23:41 UTC, joverlee521 commented on README.md
> +## Data Sources
Added more documentation to README in [230f778](https://github.com/nextstrain/counts/pull/2/commits/230f778c4db26f7e0bb1fd1bd3791e19a673eeb3).

2022-05-02 23:54 UTC, joverlee521 commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f state -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
Added notifications for new locations in [6f8c5bc](https://github.com/nextstrain/counts/pull/2/commits/6f8c5bc29be5c3844eaade25b0f6e835e863449a).

2022-05-02 23:55 UTC, joverlee521 commented on .github/workflows/update-ncov-case-counts.yaml
> +    - name: upload to S3
I've added the upload to both the public and private buckets in [9bd7086](https://github.com/nextstrain/counts/pull/2/commits/9bd708624ed351fbe53b51552ccac1d422dd8c5e).

2022-05-03 18:17 UTC, trvrb commented on .github/workflows/update-ncov-case-counts.yaml
> +    - name: upload to S3
Thank you Jover. I can imagine a situation where we, for example, want to have a `south-africa` dataset that includes sequence counts for date x clade x province and case counts for date x province. However, there's not enough sequences in GenBank to support an open data version of this analysis and it would feel strange to me to have such "distant" files in separate S3 buckets for grabbing case counts and sequence counts for an analysis (where `nextstrain-data` just has case counts and `nextstrain-ncov-private` just has sequence counts). So, yes, I do think I prefer duplication here as implemented in 9bd708624ed351fbe53b51552ccac1d422dd8c5e.

2022-05-03 18:20 UTC, trvrb commented on README.md
> +## Data Sources
Great suggestion! I use the "remote inputs" docs page all the time as well. I do have one recommendation here however: could we list the https://data.nextstrain.org/files/ncov/open/counts/global/cases.tsv.gz version instead of the `s3://nextstrain-data/files/ncov/open/counts/global/cases.tsv.gz` version in the readme? In most situations easier and faster to access over HTTPS.

2022-05-03 18:23 UTC, trvrb commented
Given "thumbs up" above, could you also reorder columns as suggested @joverlee521?

2022-05-03 18:44 UTC, huddlej commented on bin/fetch-ncov-us-case-counts
> +    csvtk replace -f state -p '([A-Z]{2,3})' -k $base/source-data/us-states.tsv -r '{kv}' --keep-key |
Cool! I like that solution a lot better.

2022-05-03 18:54 UTC, joverlee521 commented
> Given "thumbs up" above, could you also reorder columns as suggested above @joverlee521?

Yup, I've reordered the columns for clades in [bd7332d](https://github.com/nextstrain/counts/pull/2/commits/bd7332d04c280b633313f3ad477f3c93353da9b8) and for cases in [c067b4e](https://github.com/nextstrain/counts/pull/2/commits/c067b4eafb7f5759e9c452014d100c31d903cd7a).  The trial files should be updated with the new ordering.

2022-05-04 16:53 UTC, trvrb approved these changes
Thanks for attending to all of my suggestions @joverlee521 🙏

I don't have anything more in terms of PR feedback.

2022-05-04 22:30 UTC, merged